# Generated by Django 5.1.1 on 2024-09-12 12:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialty', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Hematology', 'Hematology'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Obstetrics & Gynecology', 'Obstetrics & Gynecology'), ('Oncology', 'Oncology'), ('Ophthalmology', 'Ophthalmology'), ('Orthopedics', 'Orthopedics'), ('Otolaryngology', 'Otolaryngology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Pulmonology', 'Pulmonology'), ('Rheumatology', 'Rheumatology'), ('Urology', 'Urology'), ('General Surgery', 'General Surgery'), ('Plastic Surgery', 'Plastic Surgery'), ('Infectious Disease', 'Infectious Disease'), ('General', 'General')], max_length=150)),
                ('no_patients_visited', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='create appointment date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update appointment date')),
                ('visited', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docotr', to='appointment.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_docotr', to='appointment.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
