# Generated by Django 5.1.1 on 2024-10-11 14:58

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_reviewappointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo_ID',
            field=models.ImageField(default='/avatar.png', upload_to=appointment.models.user_directory_path, verbose_name='photo id'),
        ),
    ]
