# Generated by Django 5.1.1 on 2024-09-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewappointment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='reviewappointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='reviewappointment',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='ReviewAppointment',
        ),
    ]
