# Generated by Django 5.1.1 on 2024-09-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_reviewappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='specialization',
        ),
    ]
